/* eslint-disable no-unused-vars */
/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'Noolite adapter settings' : {'en': 'Noolite adapter setting', 'ru': 'Настройки адаптера Noolite' },
	'MTRF64 device' : {'en': 'MTRF64 adapter path', 'ru': 'Путь к устройству MTRF64'},
	'Device List' : {'en' : 'Noolite Device List', 'ru' : 'Список устройств Noolite'},
	'Name' : { 'en' : 'Device name', 'ru' : 'Имя устройства'},
	'Channel' : {'en' : 'Channel number','ru' : 'Номер канала'},
	'Remote Control' : { 'en': 'Remote control device', 'ru': 'Пульт Noolite'},
	'Door Sensor' : { 'en' : 'Door Sensor', 'ru': 'Датчик открытия двери'},
	'Water Sensor': { 'en': 'Water Sensor', 'ru': 'Датчик протечки'},
	'On Off Switcher' : {'en' : 'On Off switcher', 'ru': 'Совмещенная кнопка On Off'},
	'On and Off keypad' : {'en' : 'On and Off keypad','ru' : 'Отдельные клавиши On и Off'},
	'Scenario button' : {'en' : 'Scenario button', 'ru': 'Сценарная кнопка'},
	'RGB remote control' : {'en' : 'RGB Remote control', 'ru': 'Пульт RGB'},
	'Dimmer' : { 'en' : 'Dimmer', 'ru': 'Диммер'},
	'RGB' : {'en': 'RGB ribbon', 'ru': 'RGB-лента'},
	'Switch': {'en' : 'Switch', 'ru': 'Обычное реле'},
	'Bind' : { 'en' : 'Bind', 'ru' : 'Привязка'},
	'Unbind' : { 'en' : 'Unbind', 'ru' : 'Отвязка'},
	'NooliteF' : {'en' : 'Noolite-F', 'ru': 'Noolite-F'},
	'Noolite' : { 'en' : 'Noolite', 'ru': 'Noolite'},
	'Protocol' : {'en' : 'Protocol', 'ru' : 'Протокол'},
	'Type' : {'en' : 'Device Type', 'ru' : 'Тип устройства'},
	'Link': {'en' : 'Device Bind/Unbind', 'ru': 'Привязка/Отвязка устройства'},
	'Common' : {'en': 'Common property', 'ru': 'Общие настройки'},
	'MQTT Settings': {'en' : 'MQTT Settings', 'ru' : 'Настройки MQTT'},
	'Use for input' : {'en' : 'Use MQTT for receive events from Noolite Remote control devices', 'ru': 'Использовать MQTT для получения событий от пультов Noolite'},
	'Use for output' : {'en' : 'Put into MQTT state change events of Relay', 'ru': 'Помещать в MQTT события об измении состояний на силовых блоках'},
	'Notes' : {'en' : 'MQTT topic`s name is Adapter\\DeviceName for each Noolite devices', 'ru': 'Для каждого Noolite устройства топик в MQTT имеет имя АДАПТЕР\\ИМЯУСТРОЙСТВА'},
	'Brief for bind' : {'en' : 'BEFORE make this procedure, please read manual for your Noolite device. First of all press buton on your device and them press button ob this dialog','ru': 'Пожалуйста, ПРОЧТИТЕ инструкцию к вашему Noolite устройству. Сначала нажмите кнопку на устройстве и только потом на этой панели диалога'},
	'Brief for unbind' : {'en' : 'You are sure. This device will be unpair from your MTRF64 adapter','ru': 'Вы уверены? Ваше устройство будет отсодинено от адаптера MTRF64'},
	'YesUnBind' : {'en' : 'Yes, please unbind this device', 'ru' : 'Да, нужно отвязать устройство' },
	'NoUnbind' : {'en' : 'No, I do mistake', 'ru' : 'Нет, я ошибся'},
	'YesBind' : {'en' : 'Yes, please bind this device with MTRF64 Adapter', 'ru' : 'Да, привязать устройство к адаптеру MTRF64' },
	'Nobind' : {'en' : 'No, I do mistake', 'ru' : 'Нет, я ошибся'},
	'Motion Sensor' : {'en' : 'Motion Sensor', 'ru': 'Датчик движения'},
	'Thermo Sensor' : { 'en' : 'Thermo Sensor', 'ru' : 'Датчик температуры'},
	'Description' : { 'en' : 'Description', 'ru'  : 'Описание'}
};